apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging2
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Destination cluster and namespace to deploy the application
  destination:
    server: {{ .Values.clusters.stage }}
  project: {{ .Values.project }}
  # Source of the application manifests
  source:
    path: {{ .Values.applications.guestbook.path }}
    repoURL: {{ .Values.repo }}
    targetRevision: {{ .Values.applications.guestbook.target }}
    helm:
      # Values file as block file
      values: |
        image:
          repository: gcr.io/heptio-images/ks-guestbook-demo
          tag: 0.1
        ingress:
          host: guestbook.52.255.162.155.nip.io
          canary:
            annotations:
              canary-by-header: tenantID
              canary-by-header-pattern: 10|11|12|13 # tenantID values
        metrics:
          prometheus:
            address: "http://52.149.216.245:9090"
            query: rate(nginx_ingress_controller_requests{ingress="guestbook-staging2-helm-guestbook", controller_class="nginx",exported_namespace="guestbook-staging2-helm-guestbook",status=~"[2].*"}[1h])