apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.clusters.stage }}
  project: {{ .Values.project }}
  source:
    path: {{ .Values.applications.guestbook[0].path }}
    repoURL: {{ .Values.repo }}
    targetRevision: {{ .Values.guestbook[0].target }}