apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Destination cluster and namespace to deploy the application
  destination:
    server: {{ .Values.clusters.stage }}
  project: {{ .Values.project }}
  # Source of the application manifests
  source:
    path: {{ .Values.applications.guestbook.path }}
    repoURL: {{ .Values.repo }}
    targetRevision: {{ .Values.applications.guestbook.target }}
    helm:
      # Values file as block file
      values: |
        ingress:
            host: guestbook.18.223.163.42.nip.io
        metrics:
            prometheus:
                address: "http://a0179abbebc504fe1a02cc2868d10d20-1436141555.us-east-2.elb.amazonaws.com:9090/"
        query: "|
            rate(nginx_ingress_controller_requests{ingress="eks-guestbook-helm-guestbook", controller_class="nginx",exported_namespace="eks-guestbook-helm-guestbook",status=~"[2].*"}[1h])"
