# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      # owner of the repo
      owner: byangtri
      # repository name
      repository: guestbook
      # Github will send events to following port and endpoint
      webhook:
        # endpoint to listen to events on
        endpoint: /push
        # port to run internal HTTP server on
        port: "12000"
        # HTTP request method to allow. In this case, only POST requests are accepted
        method: POST
        # url the event-source will use to register at Github.
        # This url must be reachable from outside the cluster.
        # The name for the service is in `<event-source-name>-eventsource-svc` format.
        # You will need to create an Ingress or Openshift Route for the event-source service so that it can be reached from GitHub.
        url: 
      # type of events to listen to.
      # following listens to everything, hence *
      # You can find more info on https://developer.github.com/v3/activity/events/types/
      events:
        - "*"

      # apiToken refers to K8s secret that stores the github api token
      # if apiToken is provided controller will create webhook on GitHub repo
      # +optional
      apiToken:
        # Name of the K8s secret that contains the access token
        name: github
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access token
        key: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjdiemVOUXZGSkVzNlU5T19tQ2JIY3h0Z2Q5SmVIOFl6UEJYTFJ5YWlNamsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImdpdGh1Yi10b2tlbi1ncjRjbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJnaXRodWIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5ZDQ0YjJkMy1hZDY3LTRiZjctYjdjZC1kZDVhYzQ0NDc5OTYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YXJnbzpnaXRodWIifQ.SKbPqBS7rriBmK8AJeHWXsgAk8AieihNrnFBJ6MJZoXGpi0g3LQ5_Tq8uNhBVyxYzgg4NkVUFmbDmq3gnmy7bIo5eAeJTsDWGHenU2CY6OdJA9ldTLTLnCgRrtNqKCQkEGb_NsT3sLA0kHZ3QzQxn69WF_KdVE8PEgjUncS7FZ7qvcBLuJ4BDwx-XW1-279s0yad16hgAlon-P6gvrHFDF_vGusKzuQjU6eoKcBejvZl88jBPhPlPiN0dJR9Z3eWktoevTv9B1_jzPbKiZpy-4WTDboVeAIIB8RS9RbKYaFYz1VqCbnwsuI2DpDFmoEJsnq62ZCS5D2dnqacPaxMmA

#      # webhookSecret refers to K8s secret that stores the github hook secret
#      # +optional
    #  webhookSecret:
    #    # Name of the K8s secret that contains the hook secret
    #    name: github-access
    #    # Key within the K8s secret whose corresponding value (must be base64 encoded) is hook secret
    #    key: secret

      # type of the connection between event-source and Github.
      # You should set it to false to avoid man-in-the-middle and other attacks.
      insecure: true
      # Determines if notifications are sent when the webhook is triggered
      active: true
      # The media type used to serialize the payloads
      contentType: json
      
    # example-without-api-credentials:
    #   owner: "byangtri"
    #   repository: "guestbook"
    #   webhook:
    #     endpoint: "/push"
    #     port: "13000"
    #     method: "POST"
    #   events:
    #     - "*"
    #   webhookSecret:
    #     name: github
    #     key: secret
    #   insecure: true
    #   active: true
    #   contentType: "json"

#    example-with-secure-connection:
#      owner: "argoproj"
#      repository: "argo"
#      webhook:
#        endpoint: "/push"
#        port: "13000"
#        method: "POST"
#        url: "http://myargofakeurl.fake"
#        # k8s secret that contains the cert
#        serverCertSecret:
#          name: my-secret
#          key: cert-key
#        # k8s secret that contains the private key
#        serverKeySecret:
#          name: my-secret
#          key: pk-key
#      events:
#        - "push"
#        - "delete"
#      apiToken:
#        name: github-access
#        key: token
#      webhookSecret:
#        name: github-access
#        key: secret
#      insecure: true
#      active: true
#      contentType: "json"