apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: github-eventsource-ingress
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    http:
      paths:
      - path: /
        backend:
          serviceName: github--eventsource-svc
          servicePort: 80
