apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: argoproj
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: manifests/cluster-install
    repoURL: 'https://github.com/argoproj/argo-workflows'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true