apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
          service:
            type: NodePort
        prometheusOperator:
          admissionWebhooks:
            enabled: true
    
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.2.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /spec/validation
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      jsonPointers:
        - /webhooks
      kind: ValidatingWebhookConfiguration