apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/instance: argoproj
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: sealed-secrets
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: '1.15.0-r3'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true