apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
#    successCondition: isNaN(result[0]) || result[0] >= 0.10
    successCondition: result[0] >= 0.01
    provider:
      prometheus:
        address: {{ .Values.metrics.prometheus.address }}
        query: |
          rate(nginx_ingress_controller_requests{ingress="eks-guestbook-helm-guestbook", controller_class="nginx",exported_namespace="eks-guestbook-helm-guestbook",status=~"[2].*"}[1h])