apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
#    successCondition: isNaN(result[0]) || result[0] >= 0.10
    successCondition: result[0] >= 0.01
    provider:
      prometheus:
        address: {{ .Values.metrics.prometheus.address }}
        query:  |
          {{ .Values.metrics.prometheus.query }}