{{- if .Values.rollouts.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "helm-guestbook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "helm-guestbook.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  minReadySeconds: 30
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1h # 1 hour
      - setWeight: 20
      - pause: {} # pause indefinitely
  # minReadySeconds: 30
  # strategy:
  #   canary: #Indicates that the rollout should use the Canary strategy
  #     maxSurge: "25%"
  #     maxUnavailable: 0
  #     canaryService: guestbook-canary-service
  #     stableService: {{ template "helm-guestbook.fullname" . }}
  #     # trafficRouting:
  #     #   nginx:
  #     #     # The referenced ingress will be injected with a custom action annotation, directing
  #     #     # the Nginx to split traffic between the canary and stable Service using headers
  #     #     stableIngress: {{ template "helm-guestbook.fullname" . }}
  #     #     annotationPrefix: nginx.ingress.kubernetes.io 
  #     #     {{- with .Values.ingress.canary.annotations }}
  #     #     additionalIngressAnnotations:
  #     #     {{- toYaml . | nindent 12 }}
  #     #     {{- end }}
  #     steps:
  #     # - analysis:
  #     #     templates:
  #     #     - templateName: success-rate
  #     #       clusterScope: true
  #     #     args:
  #     #     - name: service-name
  #     #       value: {{ template "helm-guestbook.fullname" . }}
  #     # Pauses indefinitely until manually resumed
  #     - setWeight: 50
  #     - pause: {}
{{- end }}
