# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# change with caution
project: 'default'
# namespace: 'seller-ads'
repo: 'https://github.com/byangtri/guestbook.git'

#ConfigMap and Secret resources in this directory
common: .common

# these are cluster addresses
clusters:
  stage: https://kubernetes.default.svc
  prod-1: https://myakscluster-a5a0451f.hcp.eastus.azmk8s.io:443

# groups describe deployment clusters of each app
groups:
  stage: ['stage']
  prod: ['prod-1']

# this is where we specify each app's configuration and destination
applications:
  guestbook:
    path: helm-guestbook
    target: HEAD