apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-chaos
spec:
  event:
    # selector: payload.message != "" && metadata["x-github-event"] = ["push"]
    selector: metadata["x-github-event"] == ["push"] && payload.message != ""
  submit:
    workflowTemplateRef:
      name: argowf-chaos-jf7ll
    arguments:
      parameters:
      - name: message
        valueFrom:
          event: payload.message