apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-chaos
  namespace: litmus
spec:
  event:
    selector: payload.message != "" && metadata["x-github-event"] = ["push"]
  submit:
    workflowTemplateRef:
      name: argowf-chaos-jf7ll
    arguments:
      parameters:
      - name: message
        valueFrom:
          event: payload.message